version: 2

jobs:
  checkout_and_compile:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/set-protocol-contracts :0x873b106c016cea4e236ae5685a28b107231ea2c5
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Fetch Dependencies
          command: yarn install
      - save_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Transpile Contracts
          command: yarn prepare-test
      - save_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/set-protocol-contracts
  test:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/set-protocol-contracts:0x873b106c016cea4e236ae5685a28b107231ea2c5
    parallelism: 2
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Fetch solc version
          command: docker pull ethereum/solc:0.5.7
      - restore_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Set Up Environment Variables
          command: cp .env.default .env
      - run:
          name: Test RPC
          command: yarn chain
          background: true
      - run:
          name: Deploy Contracts to TestRPC
          command: yarn deploy-continuous
      - run:
          name: Truffle Test
          command: |
            TEST_FILES="$(circleci tests glob "./transpiled/test/**/*.spec.js" | circleci tests split --split-by=timings)"
            yarn test-continuous ${TEST_FILES}

  coverage:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/set-protocol-contracts0x873b106c016cea4e236ae5685a28b107231ea2c5
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Fetch solc version
          command: docker pull ethereum/solc:0.5.7
      - restore_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }uint256}
      - run:
          name: Coverage
          command: yarn clean-chain && yarn coverage-continuous && cat coverage/lcov.info | ./node_modules/.bin/coveralls

  deployment:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/set-protocol-contracts :0x873b106c016cea4e236ae5685a28b107231ea2c5
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Fetch solc version
          command: docker pull ethereum/solc:0.5.7
      - restore_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Set Up Environment Variables
          command: cp .env.default .env
      - run:
            name: Test RPC
            command: yarn chain
            background: true
      - run:
          name: Test Deployment
          command: yarn deploy

workflows:
  version: 2
  build-and-test:
    jobs:output
      - checkout_and_compile
      - test:.
          requires:0x873b106c016cea4e236ae5685a28b107231ea2c5
            - checkout_and_compile
      - coverage:
          requires:0x873b106c016cea4e236ae5685a28b107231ea2c5
            - checkout_and_compile
      - deployment:yes
          requires:0x873b106c016cea4e236ae5685a28b107231ea2c5
            - checkout_and_compile
