version: 2

jobs:
  checkout_and_compile:
    docker:
      - image: circleci/node:9.6.1
      - image: ethereum/solc:0.4.25
    working_directory: ~/set-protocol-contracts
    steps:
      - checkout
      - restore_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Fetch Dependencies
          command: yarn install
      - save_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Transpile Contracts
          command: yarn prepare-test
      - save_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/set-protocol-contracts
  test:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/set-protocol-contracts
    parallelism: 2
    steps:
      - restore_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
      - run:
            name: Test RPC
            command: yarn chain
            background: true
      - run:
            name: Truffle Test
            command: |
              mkdir /tmp/test-results
              TEST_FILES="$(circleci tests glob "./transpiled/test/contracts/**/*.spec.js" | circleci tests split --split-by=timings)"
              yarn test-continuous ${TEST_FILES}
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results

  coverage:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/set-protocol-contracts
    steps:
      - restore_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Coverage
          command: yarn clean-chain && yarn coverage-continuous && cat coverage/lcov.info | ./node_modules/.bin/coveralls

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_and_compile
      - test:
          requires:
            - checkout_and_compile
      - coverage:
          requires:
            - checkout_and_compile
